services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
      MYSQL_USER: jobs
      MYSQL_PASSWORD: jobs
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8080:8080"
  api:
    build: ./api
    environment:
      DATABASE_URL: mysql+pymysql://jobs:jobs@db:3306/jobs
      LOG_LEVEL: info
      SCHEDULER_ENABLED: "false"
    volumes:
      - ./api:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - api
  worker:
    build: ./worker
    environment:
      API_URL: http://api:8000
      SCRAPE_HTML_ENABLED: "false"
      GH_COMPANY: openai
      SCRAPE_DELAY: "2.5"
    depends_on:
      - api
volumes:
  mysqldata:
